version: "3"

tasks:
  install-deps:
    desc: Install Go dependencies
    cmds:
      - cd agent && go mod download
      - cd cli && bun install

  build-wasm:
    desc: Build the Go WASM binary
    deps: [install-deps]
    cmds:
      - cd agent && GOOS=js GOARCH=wasm go build -o bin/wasmlib/bin.wasm ./pkg/wasmlib/main.go
      - cd agent && cp "$(go env GOROOT)/lib/wasm/wasm_exec.js" bin/wasmlib
      - mkdir -p cli/wasm
      - cp agent/bin/wasmlib/bin.wasm cli/wasm/
      - cp agent/bin/wasmlib/wasm_exec.js cli/wasm/

  build-cli:
    desc: Build and copy cli
    deps: [build-wasm]
    cmds:
      - cp ./agent/internal/db/queries/introspect_pg.sql ./cli/sql_functions/introspect_pg.sql
      # - cd cli && bun run build
      # - cd cli && npm publish

  publish-cli:
    desc: Build and publish CLI to GitHub Packages
    deps: [build-cli]
    cmds:
      - cd cli && bun build index.ts --compile --outfile dist/pg_track_events wasm/**
