track:
  user.insert:
    event: "user_signup"
    properties:
      id: "new.id"
      email: "new.email"
      name: "new.name"
      # data: "new.data"
      # data_inner: "new.data.inner"

  # user.update:
  #   event: "user_updated"
  #   properties:
  #     id: "new.id"
  #     email: "new.email"
  #     name: "new.name"

  user.update:
    cond: "old.email != new.email ? events.user_changed_email : events.user_updated"
    "user_changed_email":
      event: "user_changed_email"
      properties:
        id: "new.id"
        previous_email: "old.email"
        new_email: "new.email"
    "user_updated":
      event: "user_updated"
      properties:
        id: "new.id"
        email: "new.email"
        name: "new.name"
        # data: "new.data"
        # data_inner: "new.data['inner']"

destinations:
  posthog:
    apiKey: "$POSTHOG_API_KEY"
    filter: "*"
  mixpanel:
    apiKey: "$MIXPANEL_PROJECT_TOKEN"
    filter: "*"
  amplitude:
    apiKey: "$AMPLITUDE_API_KEY"
    filter: "*"
