track:
  user.insert:
    event: "user_signup"
    properties:
      id: "new.id"
      email: "new.email"
      name: "new.name"
      # data: "new.data"
      # data_inner: "new.data.inner"

  # user.update:
  #   event: "user_updated"
  #   properties:
  #     id: "new.id"
  #     email: "new.email"
  #     name: "new.name"

  user.update:
    cond: "old.email != new.email ? events.user_changed_email : events.user_updated"
    "user_changed_email":
      event: "user_changed_email"
      properties:
        id: "new.id"
        previous_email: "old.email"
        new_email: "new.email"
    "user_updated":
      event: "user_updated"
      properties:
        id: "new.id"
        email: "new.email"
        name: "new.name"
        # data: "new.data"
        # data_inner: "new.data['inner']"

destinations:
  posthog:
    filter: "*"
    apiKey: "$POSTHOG_API_KEY"
  mixpanel:
    filter: "*"
    projectToken: "$MIXPANEL_PROJECT_TOKEN"
  amplitude:
    filter: "*"
    apiKey: "$AMPLITUDE_API_KEY"
  bigquery:
    filter: "*"
    tableId: "$BIGQUERY_TABLE_ID"
    credentialsJson: "$BIGQUERY_CREDENTIALS_JSON"

ignore:
  auth_authenticator: "*" # This ignores all columns in the auth_authenticator table
  auth_account: ["id_token", "refresh_token", "access_token"] # This ignores only specific columns in the auth_account table
  auth_verification_token: ["token"] # This ignores only specific columns in the auth_verification_token table
