track:
  user.insert:
    event: "user_signup"
    properties:
      id: "new.id"
      email: "new.email"
      name: "new.name"
      # data: "new.data"
      # data_inner: "new.data.inner"

  # user.update:
  #   event: "user_updated"
  #   properties:
  #     id: "new.id"
  #     email: "new.email"
  #     name: "new.name"

  user.update:
    cond: "old.email != new.email ? events.user_changed_email : events.user_updated"
    "user_changed_email":
      id: "new.id"
      previous_email: "old.email"
      new_email: "new.email"
    "user_updated":
      id: "new.id"
      email: "new.email"
      name: "new.name"
      # data: "new.data"
      # data_inner: "new.data['inner']"

destinations:
  posthog:
    filter: "*"
    apiKey: "$POSTHOG_API_KEY"
  mixpanel:
    filter: "*"
    projectToken: "$MIXPANEL_PROJECT_TOKEN"
  amplitude:
    filter: "*"
    apiKey: "$AMPLITUDE_API_KEY"
  bigquery:
    filter: "*"
    tableId: "$BIGQUERY_TABLE_ID"
    credentialsJson: "$BIGQUERY_CREDENTIALS_JSON"

raw_db_event_destinations:
  bigquery:
    filter: "*"
    tableId: "$BIGQUERY_RAW_DB_EVENTS_TABLE_ID"
    credentialsJson: "$BIGQUERY_CREDENTIALS_JSON"
  s3:
    filter: "*"
    bucket: "$S3_BUCKET"
    endpoint: "$S3_ENDPOINT"
    region: "$S3_REGION"
    rootDir: "$S3_ROOT_DIR"
    accessKey: "$S3_ACCESS_KEY"
    secretKey: "$S3_SECRET_KEY"

ignore:
  auth_authenticator: "*" # This ignores all columns in the auth_authenticator table
  auth_account: ["id_token", "refresh_token", "access_token"] # This ignores only specific columns in the auth_account table
  auth_verification_token: ["token"] # This ignores only specific columns in the auth_verification_token table
  user: ["hashed_password"]
